/**
 * AEGIS Phase 2 - Report Generator
 * Generates REPORT.md with penetration test findings
 */

import { generateSummary, type VulnerabilityResult } from "../ai/pentestAI.js";
import type { ScanResult } from "../scanner/index.js";
import * as fs from "fs";
import * as path from "path";

function severityBadge(severity: string): string {
  const badges: Record<string, string> = {
    Critical: "![Critical](https://img.shields.io/badge/Critical-red)",
    High: "![High](https://img.shields.io/badge/High-orange)",
    Medium: "![Medium](https://img.shields.io/badge/Medium-yellow)",
    Low: "![Low](https://img.shields.io/badge/Low-blue)",
    Info: "![Info](https://img.shields.io/badge/Info-gray)",
  };
  return badges[severity] || severity;
}

function formatDuration(ms: number): string {
  const seconds = Math.floor(ms / 1000);
  const minutes = Math.floor(seconds / 60);
  if (minutes > 0) {
    return `${minutes}m ${seconds % 60}s`;
  }
  return `${seconds}s`;
}

function escapeMarkdown(text: string): string {
  return text.replace(/[|`]/g, "\\$&");
}

export async function generateReport(
  result: ScanResult,
  outputPath?: string
): Promise<string> {
  const vulnerabilities = result.vulnerabilities.filter(v => v.vulnerable);
  
  // Generate AI summary
  let executiveSummary = "";
  try {
    executiveSummary = await generateSummary(result.target, result.vulnerabilities);
  } catch {
    executiveSummary = "Executive summary generation failed. Please review findings manually.";
  }

  const report = `# AEGIS Security Assessment Report

## Target Information

| Property | Value |
|----------|-------|
| **Target URL** | ${result.target} |
| **Scan Date** | ${result.startTime.toISOString()} |
| **Duration** | ${formatDuration(result.duration)} |
| **Total Tests** | ${result.totalTests} |
| **Vulnerabilities Found** | ${vulnerabilities.length} |

---

## Executive Summary

${executiveSummary}

---

## Vulnerability Summary

| Severity | Count |
|----------|-------|
| ${severityBadge("Critical")} Critical | ${result.summary.critical} |
| ${severityBadge("High")} High | ${result.summary.high} |
| ${severityBadge("Medium")} Medium | ${result.summary.medium} |
| ${severityBadge("Low")} Low | ${result.summary.low} |
| ${severityBadge("Info")} Info | ${result.summary.info} |

---

## Detailed Findings

${vulnerabilities.length === 0 ? "*No vulnerabilities found.*" : vulnerabilities.map((v, i) => `
### ${i + 1}. ${v.name}

| Property | Value |
|----------|-------|
| **Category** | ${v.category} |
| **Severity** | ${severityBadge(v.severity)} |
| **Endpoint** | \`${v.endpoint}\` |
| **OWASP** | ${v.owasp || "N/A"} |
| **CWE** | ${v.cwe || "N/A"} |

**Payload:**
\`\`\`
${escapeMarkdown(v.payload)}
\`\`\`

**Evidence:**
${v.evidence}

**Recommendation:**
${v.recommendation}

---
`).join("\n")}

## OWASP Top 10 Coverage

| Category | Status |
|----------|--------|
| A01:2021 - Broken Access Control | ${vulnerabilities.some(v => v.owasp?.includes("A01")) ? "Vulnerable" : "Tested"} |
| A02:2021 - Cryptographic Failures | ${vulnerabilities.some(v => v.owasp?.includes("A02")) ? "Vulnerable" : "Tested"} |
| A03:2021 - Injection | ${vulnerabilities.some(v => v.owasp?.includes("A03")) ? "Vulnerable" : "Tested"} |
| A04:2021 - Insecure Design | ${vulnerabilities.some(v => v.owasp?.includes("A04")) ? "Vulnerable" : "Tested"} |
| A05:2021 - Security Misconfiguration | ${vulnerabilities.some(v => v.owasp?.includes("A05")) ? "Vulnerable" : "Tested"} |
| A06:2021 - Vulnerable Components | ${vulnerabilities.some(v => v.owasp?.includes("A06")) ? "Vulnerable" : "Tested"} |
| A07:2021 - Auth Failures | ${vulnerabilities.some(v => v.owasp?.includes("A07")) ? "Vulnerable" : "Tested"} |
| A08:2021 - Data Integrity Failures | ${vulnerabilities.some(v => v.owasp?.includes("A08")) ? "Vulnerable" : "Tested"} |
| A09:2021 - Logging Failures | ${vulnerabilities.some(v => v.owasp?.includes("A09")) ? "Vulnerable" : "Tested"} |
| A10:2021 - SSRF | ${vulnerabilities.some(v => v.owasp?.includes("A10")) ? "Vulnerable" : "Tested"} |

---

## Remediation Priority

${vulnerabilities
  .sort((a, b) => {
    const order = { Critical: 0, High: 1, Medium: 2, Low: 3, Info: 4 };
    return order[a.severity] - order[b.severity];
  })
  .slice(0, 5)
  .map((v, i) => `${i + 1}. **[${v.severity}]** ${v.name} - ${v.recommendation.substring(0, 100)}...`)
  .join("\n") || "*No immediate remediation required.*"}

---

## Self-Healing Actions

The following vulnerabilities were automatically reported to AEGIS Phase 3 for self-healing:

${vulnerabilities.map(v => `- [${v.severity}] ${v.category} at \`${v.endpoint}\` - Healing Applied`).join("\n") || "*No self-healing actions triggered.*"}

---

*Report generated by AEGIS Phase 2 - AI-Powered Penetration Testing*
*Scan completed at: ${result.endTime.toISOString()}*
`;

  // Write to file if path provided
  if (outputPath) {
    const dir = path.dirname(outputPath);
    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true });
    }
    fs.writeFileSync(outputPath, report);
  }

  return report;
}

/**
 * Generate JSON report for programmatic access
 */
export function generateJSONReport(result: ScanResult): string {
  return JSON.stringify({
    meta: {
      target: result.target,
      startTime: result.startTime.toISOString(),
      endTime: result.endTime.toISOString(),
      duration: result.duration,
      totalTests: result.totalTests,
    },
    summary: result.summary,
    vulnerabilities: result.vulnerabilities.filter(v => v.vulnerable),
  }, null, 2);
}
