def generate_report(results):
    from datetime import datetime
    import os
    
    # Ensure reports directory exists
    os.makedirs("reports", exist_ok=True)
    
    with open("reports/report.md", "w", encoding="utf-8") as f:
        f.write(f"# AEGIS Security Analysis Report\n\n")
        f.write(f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
        f.write(f"**Status:** {'⚠️ ISSUES DETECTED' if results else '✅ CLEAN'}\n\n")
        f.write("---\n\n")
        
        f.write("## 🏗️ 1. ARSITEKTUR (Architecture)\n")
        f.write("The AEGIS Security Engine follows a three-layered approach:\n")
        f.write("1. **Scanner Layer**: Uses regex-based pattern matching to identify hardcoded secrets and dangerous functions.\n")
        f.write("2. **Healing Layer**: Automatically remediates issues by migrating secrets to environment variables.\n")
        f.write("3. **Reporting Layer**: Aggregates findings into actionable insights.\n\n")
        f.write("---\n\n")

        f.write("## 🔍 2. CELAH (Vulnerabilities)\n")
        if not results:
            f.write("### ✅ No Vulnerabilities Found\n\n")
        else:
            f.write(f"### ⚠️ {len(results)} Vulnerabilities Detected\n\n")
            for item in results:
                f.write(f"#### 🔴 {item['issue']}\n")
                f.write(f"- **File:** {item['file']}\n\n")

        f.write("---\n\n")

        f.write("## 💡 3. REKOMENDASI (Recommendations)\n")
        f.write("1. **Secret Management**: Use .env files for all sensitive keys.\n")
        f.write("2. **Code Hardening**: Avoid dynamic code execution like eval() or exec().\n")
        f.write("3. **Continuous Security**: Run AEGIS Phase 1 scan before every commit.\n\n")
        
        f.write("---\n")
        f.write("*Report generated by AEGIS Security CLI - Phase 1*\n")